cache: apt

before_install:
    - sudo bash -c 'URL=http://download.bareos.org/bareos/experimental/nightly/xUbuntu_12.04/; wget -q $URL/Release.key -O- | apt-key add -; echo "deb $URL /" >> /etc/apt/sources.list.d/bareos.list'
    - sudo apt-get update -qq
    - sudo apt-get install -qq make texlive-latex-extra tex4ht imagemagick python bareos bareos-database-sqlite3

script:
    - make pdf
    - make check
    - make html
    - make check
