language: php

php:
	- 5.5
	- 5.4
	- 5.3

env:
	- DB=mysql
	- DB=pgsql

before_install:
	- composer self-update
	- composer update --prefer-source --dev

before_script:

script:

after_script:

notifications:
