cache: apt

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq make texlive-latex-extra tex4ht imagemagick

script:
    - make pdf
    - make check
    - make html
    - make check
